### ISSUE TITLE
BME280 Support geplant?

### ISSUE THREAD

**Issue by gerdfinder** [jp112sdl/WemosD1_HomeMatic_WiFiSensor#1]
Danke für die sehr ausführlich beschriebenen Progarmme.

Beim WiFi Sensor hätte ich den Wunsch nach dem genaueren BME280 Sensor,
der zudem noch den Luftdruck misst.
Dann noch den Helligkeitssensor mit rein und der Aussensensor wäre (für mich) komplett.
Ist das machbar oder in Planung?

**Comment by jp112sdl** [comment]
Hallo @gerdfinder,

nein, sowas ist nicht geplant.

Für ein solches Multi-Sensor Projekt ist wohl [ESPEasy](https://www.letscontrolit.com/wiki/index.php/Devices) besser geeignet.
Es lässt sich zwar nicht so elegant in HomeMatic integrieren, weil man die Werte zyklisch vom Wemos abfragen müsste (per Skript), aber es ist recht unkompliziert.
