### ISSUE TITLE
Klappt leider nicht

### ISSUE THREAD

**Issue by KJSBO** [jp112sdl/WemosD1_HomeMatic_WiFiSensor#2]
![tempsensor](https://user-images.githubusercontent.com/36269329/36035690-f3dc5c24-0db7-11e8-9e1f-4a2f1feacc5e.JPG)
Hallo, habe (wohl kurz vor der Entscheidung, das Projekt einzustellen) die Teile für den HM-Temperatur-Sensor bestellt. Heute habe ich die Teile dann zusammengebaut (mit DHT22/AM2302), geflashed, konfiguriert, in CuxD/HM eingebunden. Hat alles geklappt. Nur leider bekomme ich keine Temperatur angezeigt. Da steht immer "0°". 
Ich habe die anleitung mehrfach gechecked, 2 DHT22/AM2302 ausprobiert und alle Lötstellen mehrfach geprüft.
Hast du noch eine Idee, was Ursache für die "Nicht-Anzeige" sein könnte? 
VG Kurt

**Comment by jp112sdl** [comment]
Kannst du mit einem Terminal-Programm mal die seriellen Meldungen (115200 Baud) des Wemos protokollieren?

**Comment by KJSBO** [comment]
Erwischt :-(
Ich habe das Ganze nach der guten Anleitung gemacht, aber mein Wissen ist begrenzt.
Wie kann ich das Loggen denn anstossen?

**Comment by jp112sdl** [comment]
- Wemos an PC anschließen
- [Putty](https://the.earth.li/~sgtatham/putty/latest/w32/putty.exe) runterladen, starten, "Serial" auswählen, COM Port eintragen, bei Speed 115200, dann Open klicken
- kleinen schwarzen Reset Taster am Wemos drücken
- gucken was in Putty kommt

**Comment by KJSBO** [comment]
reset wird kurz blau bestätigt. Nach Klicken auf open in putty passiert aber: nix.

![puttywemos](https://user-images.githubusercontent.com/36269329/36036619-9c0d06da-0dba-11e8-9072-f7a4780f3db7.JPG)

**Comment by jp112sdl** [comment]
Oben bei Session Serial auswählen

**Comment by jp112sdl** [comment]
![launch putty](https://user-images.githubusercontent.com/18190139/36037034-cd110e60-0dbb-11e8-864e-b29f87ceaed1.png)

**Comment by jp112sdl** [comment]
Bei Serial line kommt COM4 rein und bei Speed 115200, dann Open

**Comment by KJSBO** [comment]
oh, da war ich an der falschen Stelle...
Output sieht nach jedem reset anders aus. Z.B.
![wputty2](https://user-images.githubusercontent.com/36269329/36037195-480daeca-0dbc-11e8-8769-4eaecd4fcfe3.JPG)
![wputty1](https://user-images.githubusercontent.com/36269329/36037197-48303c10-0dbc-11e8-8122-8060e2a359d4.JPG)

**Comment by jp112sdl** [comment]
Ah, in dem Projekt muss serielles Debugging erst noch aktiviert werden.
Du muss D5 an GND brücken.
Danach versuchs noch mal.

**Comment by KJSBO** [comment]
![wputty](https://user-images.githubusercontent.com/36269329/36037793-1820a9b8-0dbe-11e8-882c-69755738b574.JPG)

**Comment by jp112sdl** [comment]
Fehler -1
Connect Timeout -> Der Wemos kann deine CCU nicht erreichen.

**Comment by KJSBO** [comment]
mmh, Wemos und CCU sind im selben Netz. Auf der CCU ist der Zugang für die Wemos-IP frei geschaltet. Wenn ich den HTTP-Befehl z.B. vom Handy aus absetze klappt es.
Hast du ggf. noch eine Idee?

**Comment by jp112sdl** [comment]
Probier es mal mit der Version hier

[WemosD1_HomeMatic_WiFiSensor.ino.d1_mini.bin.zip](https://github.com/jp112sdl/WemosD1_HomeMatic_WiFiSensor/files/1711823/WemosD1_HomeMatic_WiFiSensor.ino.d1_mini.bin.zip)

**Comment by KJSBO** [comment]
Hab das neue Image geflashed und dann neu konfiguriert. Leider keine Änderung, immer noch Fehler -1.

**Comment by jp112sdl** [comment]
HTTPC_ERROR_CONNECTION_REFUSED (-1)

Kannst höchstens mal noch nen Screenshot von deinen Firewalleinstellungen der CCU schicken... aber dann bin ich auch mit meinem Latein am Ende :/

**Comment by KJSBO** [comment]
ich kann den Wemos auch nicht anpingen. Werde mal in dieser Richtung weiter suchen.
Vielen Dank schon mal für deine Unterstützung!!!!

**Comment by KJSBO** [comment]
Hallo, sorry, ich bin's nochmal. Ich hatte festgestellt, dass ich wohl kein Original-WemosD1 eingesetzt hatte und habe mir ein Original besorgt. Am Ergebnis hat das leider nichts geändert. Was mir aber auffällt ist, dass die Konfigurationseinstellungen im Wemos nun nicht mehr abgespeichert werden. Die HTTP-Befehle enthalten nun die CCU-ip nicht mehr. Was kann das denn jetzt wieder sein?
![wputty](https://user-images.githubusercontent.com/36269329/36165156-e49f47fa-10ee-11e8-907d-b49c3682b8dd.JPG)

**Comment by jp112sdl** [comment]
Eigentlich ist das Projekt end of life.
Hab gesehen, dass es einen Bug ([514](https://github.com/tzapu/WiFiManager/issues/514)) im WiFiManager und/oder dem ESP8266 Core gibt.

Hab jetzt noch einen letzten Versuch gemacht. 
Nimm mal bitte die angehängte Firmware.

[WemosD1_HomeMatic_WiFiSensor.ino.d1_mini.bin.zip](https://github.com/jp112sdl/WemosD1_HomeMatic_WiFiSensor/files/1721749/WemosD1_HomeMatic_WiFiSensor.ino.d1_mini.bin.zip)

**Comment by jp112sdl** [comment]
Der Fehler liegt doch im ESP8266 Core.
Folgender Fix behebt das Problem: esp8266/Arduino#4350

**Comment by KJSBO** [comment]
...ich war schon stolz auf mich, dass ich deine Anleitung zum Zusammenbau und flashen des Wemos einigermassen unfallfrei umsetzen konnte. Das war mein erster Kontakt zum Wemos überhaupt. 
Die Programmieranweisungen im o.g. Link kann ich (auf Basis meines Wissens aus anderen Programmiersprachen) einigermassen folgen, aber ich habe keine Ahnung, wie ich das nun umsetze.
Da ich dir ja nun nicht länger auf den Keks gehen möchte, habe ich dieses Projekt fast schon abgeschrieben. Vielleicht hast du ja andere -aktuelle- Projekte im Zusammenhang mit Homematic, die ähnlich interessant sind!?

**Comment by jp112sdl** [comment]
Du brauchst nichts umsetzen... 
Einfach die .bin flashen, die ich in meinem vorletzten Beitrag mit angehängt habe...

**Comment by Josus90** [comment]
Hallo Kurt,
klappt bei dir die Verbindung zur CCU mit der neuen Firmware? Bei mir wird die CCU-IP nur zur hälfte übernommen (192.168.). Sonst widme ich mich jetzt doch lieber AskSinPP und verwende den DHT22 dafür.
Schönen Gruß Jonas

**Comment by jp112sdl** [comment]
Moin.

> Sonst widme ich mich jetzt doch lieber AskSinPP und verwende den DHT22 dafür.

Kann ich nur empfehlen.

**Comment by Josus90** [comment]
Okay hab es hinbekommen. Bei mir hat es gereicht die CCU-IP direkt im Sketch zu ändern und dann die neue/abgeädnerte Binärdatei zu flashen. Nichtsdestotrotz sind Pro Mini/CC1101 auf dem Weg zu mir ;)
